[Rule]

# DIRECT
DOMAIN-SUFFIX,erpshop.duanxiaoli.com,DIRECT
DOMAIN-SUFFIX,lianlianpay.com,DIRECT
DOMAIN-SUFFIX,zhejiang.chinatax.gov.cn,DIRECT
DOMAIN-SUFFIX,duanxiaoli.com,DIRECT
DOMAIN-SUFFIX,xunlei.com,DIRECT
DOMAIN-SUFFIX,shandai.net,DIRECT
DOMAIN-SUFFIX,youdao.com,DIRECT
DOMAIN-SUFFIX,xtransfer.com,DIRECT
DOMAIN-SUFFIX,zj96596.com,DIRECT
DOMAIN-SUFFIX,ljcdn.com,DIRECT

